name: Build Components

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run build
        run: node build.js

      - name: Commit dist files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: rebuild dist [skip ci]"
          token: ${{ secrets.HM_COMP }}
          file_pattern: dist/
